spring.application.name=backend

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/finanzas_bd}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:financeflux}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Fx9#m2W!}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Inicialización de datos
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Servidor
server.port=8081

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html